---
title: "report"
output: pdf_document
date: "2022-11-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
```

## Section 1

```{r}
df <- read_excel("covid_data.xlsx")
# renaming columns:
colnames(df)[1] = "hours_before"
colnames(df)[2] = "hours_after"
colnames(df)[3] = "school"
colnames(df)[4] = "job"
colnames(df)[5] = "music"
colnames(df)[6] = "family_friends"
colnames(df)[7] = "games"
colnames(df)[8] = "movies_TV"
colnames(df)[9] = "other"
colnames(df)[10] = "devices"
colnames(df)[11] = "wifi"
colnames(df)[12] = "covid_access"
colnames(df)[13] = "covid_interruption"
colnames(df)[14] = "country"
colnames(df)[16] = "age"
# dropping first row
df <- df[-1,]
```

```{r}
library(dplyr)

df <- df %>% 
  mutate(num_hours_before = case_when(
    hours_before == "8+ horas" ~ 5,
    hours_before == "5-8 horas" ~ 4,
    hours_before == "3-5 horas" ~ 3,
    hours_before == "1-3 horas" ~ 2,
    hours_before == "Menos de 1 hora" ~ 1
  ))

df <- df %>% 
  mutate(num_hours_after = case_when(
    hours_after == "8+ horas" ~ 5,
    hours_after == "5-8 horas" ~ 4,
    hours_after == "3-5 horas" ~ 3,
    hours_after == "1-3 horas" ~ 2,
    hours_after == "Menos de 1 hora" ~ 1
  ))

df <- df %>% 
  mutate(num_age = case_when(
    age == "66 años o más" ~ 6,
    age == "56-65 años" ~ 5,
    age == "46-55 años" ~ 4,
    age == "36-45 años" ~ 3,
    age == "26-35 años" ~ 2,
    age == "19-25 años" ~ 1,
  ))
```

```{r}
library(ggplot2)

df %>%
  group_by(age) %>%
  summarize(mean = mean(num_hours_before)) %>%
  ggplot(aes(x = age , y= mean)) + 
  geom_bar(stat = "identity") + 
  labs(title="Age by Technology Usage Pre-Pandemic",
        x ="Average Age", y = "Technology Usage (hrs)")
```

Age Categories: 0 corresponds to  

```{r}
df %>%
  group_by(age) %>%
  summarize(mean = mean(num_hours_after)) %>%
  ggplot(aes(x = age , y= mean)) + 
  geom_bar(stat = "identity") + 
  labs(title="Age by Technology Usage Post-Pandemic",
        x ="Average Age", y = "Technology Usage (hrs)")
```

```{r}
lm_tech = lm(num_hours_after ~ num_age, df)
summary(lm_tech)

lm_tech_1 = lm(num_hours_after, df)
# statistically significant that older people use tech less 
```
```{r}
set.seed(0)
t.test(df$num_hours_after - df$num_hours_before, mu = 0)
# p-value is significant -> there statistically significant difference between # hours before pandemic and # hours after pandemic -> ppl used tech more after (0.55)  
```
```{r}
df2 <- df %>%
  filter(!is.na(job))

t.test(df2$num_hours_after - df2$num_hours_before, mu = 0)

# diff in hours for ppl who only use tech for job 
```
```{r}
df3 <- df %>%
  filter(!is.na(music))

t.test(df3$num_hours_after - df3$num_hours_before, mu = 0)
```

```{r}
df4 <- df %>%
  filter(!is.na(family_friends))

t.test(df4$num_hours_after - df4$num_hours_before, mu = 0)
```

```{r}
df5 <- df %>%
  filter(!is.na(games))

t.test(df5$num_hours_after - df5$num_hours_before, mu = 0)
```

```{r}
df6 <- df %>%
  filter(!is.na(movies_TV))

t.test(df6$num_hours_after - df6$num_hours_before, mu = 0)
```

```{r}
df7 <- df %>%
  filter(!is.na(other))

t.test(df7$num_hours_after - df7$num_hours_before, mu = 0)

# talk about differences between the two categories
```
